### ISSUE TITLE
Mutability Question

### ISSUE THREAD

**Issue by EduardoLR10** [dsorokin/aivika#6]
Do you see a reason why you have to use `IO`, instead of wrapping the mutations inside a pure abstraction, e.g., `ST`? An example of a use case would be to execute memoization. What would be the concerns with swapping the abstraction?

**Comment by dsorokin** [comment]
Please try using my another package aivika-transformers. This is a generalization of the aivika package. For example, you could try to instantiate aivika-transformers for using it with ST (or some derivative), although I'm not quite sure that everything would have fully-featured equivalents in ST. 

So, the exception handling within ST is questionable. But the aivika-transformers constraints require exception handling. Then you could provide some stub that would not use exceptions and so on.
